# Generated by Django 3.2.5 on 2021-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_post_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
