# Generated by Django 3.2.5 on 2021-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
