# Generated by Django 3.2.5 on 2021-07-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20210717_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
