# Generated by Django 3.2.5 on 2021-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20210717_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
