# Generated by Django 3.2.5 on 2021-07-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_album_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_year',
        ),
    ]
