# Generated by Django 3.2.5 on 2021-07-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_remove_album_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
