# Generated by Django 3.2.5 on 2021-07-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_album_album_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_year',
            new_name='year',
        ),
    ]
