# Generated by Django 3.2.5 on 2021-07-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20210718_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
