# Generated by Django 3.2.5 on 2021-07-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_album_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
