# Generated by Django 3.2.5 on 2021-07-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['artist']},
        ),
    ]
