# Generated by Django 3.2.5 on 2021-07-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_alter_artist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
