# Generated by Django 3.2.5 on 2021-07-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0018_auto_20210719_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
