# Generated by Django 3.2.5 on 2021-07-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0021_auto_20210719_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
