# Generated by Django 3.2.5 on 2021-07-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0022_rename_artist_name_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
