# Generated by Django 3.2.5 on 2021-07-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0024_remove_album_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
