# Generated by Django 3.2.5 on 2021-07-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0026_auto_20210719_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
