# Generated by Django 3.2.5 on 2021-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0029_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
