# Generated by Django 3.2.5 on 2021-07-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0030_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
