# Generated by Django 3.2.5 on 2021-07-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0032_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
    ]
