# Generated by Django 3.2.5 on 2021-07-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0034_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['artist']},
        ),
    ]
