# Generated by Django 3.2.5 on 2021-07-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0035_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['album_artist']},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='album_artist',
        ),
    ]
