# Generated by Django 3.2.5 on 2021-07-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0040_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
